language: python
python:
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: chekos
  password:
    secure: LRs58NuThEDtaeo4/qXsdWukYT9imYfIiByMyL7Z/vCXkJTnqrIpufZh1Fg2xMnzjoN3pIFA21RyAoTGRnuv53o+Z4pei71jdTvUJNssKT4QQTTM+IdxAz6OmvLA/0uA/Zh1sfq58ACe/A4OlUM71vuikyBP9t4CvcNz9+mWVxLfQ5fHLEJxKCXxGJwsWC+rd+jJbI73j1rHitvuRF5ilnNYwDOiAg8I18hiCpOLQAmE+DGn2ZTcd0jgfg6kJedxeqaFFbLAbASnqdPG12y3YgfHLyzlcEFqXYfZE41KKYG1kWH5fyGWHGTBBW/H4Jmm4avIieTDQ3oXwPuawVA6QJ0MdOAH/WoBtUdE/LjccZeW54DqeoC0DULvkUfy4R0WH8E+KzwJ5mV4dOCRUWOrMbcsHfZAT9YGmzk91YtcSGCd+XG4CpUsL+76UIMJlC6qbnorSQlIJsDRqG6CX79l+mUGIpVnQW17YT5E4BF4zabBJ6aEP6barWQZs++WqvVvpOwBuGZQWre4X8cZATQYSKrsimOURWei572IPbHovbpCPvQRG189SnbEtbLCiAY3cbbR0MolAOgLMNCXe4Ks/OIJ3Ihc5Ejrjpx43hvoCj61f+zo/f9V5nZSSEFKRoX4MBEYdjbxKTZoDYJJy/GZ3XPJH+T4Rexym/VKSQPVRBE=
  on:
    tags: true
    repo: chekos/acs_download
    python: 3.6
